kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: Nov14Pradee
  namespace: test-nov14-new
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./Nov14Pradee-spec.json
  policy-sequence:
    - $ref: test-nov14-new:webM:1.0
