kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: webM
  namespace: test-nov14-new
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: test-nov14-new:default-invoke-policy-webM:1.0
