kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: API_LB
  namespace: LB_project_test
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./API_LB-spec.json
  policy-sequence:
    - $ref: LB_project_test:webm:1.0
