kind: LoadBalancer
apiVersion: api.ibm.com/v1
metadata:
  name: LB
  namespace: LB_project_test
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  input: test
  roundRobinHttp:
    verb: GET
    endpoints:
      - endpoint:
          name: endpoint
          tlsClientProfile: ''
          url: http://localhost:5000
          urlType: jsonata
          version: HTTP/1.1
          timeout: 30
          compressRequest: none
          decompressResponse: false
          followRedirects: false
          chunkedUpload: false
          persistentConnections: true
        suspendTimeout: 30
  extensions:
    webm-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        endpoints:
          - name: endpoint
            connectionTimeout: 30
            sslConfig:
              keyStoreAlias: ''
              keyAlias: ''
              trustStoreAlias: ''
            serviceRegistryParameters: []
  output: test
