kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: webm
  namespace: LB_project_test
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: LB_project_test:default-invoke-policy-webm:1.0
    - $ref: LB_project_test:LB:1.0
